### ISSUE TITLE
Deploy as Windows Installer (MSI) file

### ISSUE THREAD

**Issue by pastewka** [livMatS/dtool-lookup-gui#119]
Starting the GUI on Windows can take a long time, apparently because it is extracting into a temporary directory and then launching it. We should target installation into the `Programs` directory to avoid the extraction step. And option would be to deployment as an .msi file.

**Comment by pastewka** [comment]
This may help: https://www.pythonguis.com/tutorials/packaging-pyqt5-pyside2-applications-windows-pyinstaller/

**Comment by jotelha** [comment]
Can we live with an .exe installer instead of an .msi? In that case, https://github.com/livMatS/dtool-lookup-gui/pull/135 does the job. I looked at InstallForge from the Qt tutorial above, it's not scriptable. The Microsoft-recommended "Wix" for creating msi installers is way too complex, Inno Setup here is preinstalled on github's windows runner and easily scriptable, works fine in CI.

**Comment by jotelha** [comment]
Ok, then I close this one with merging https://github.com/livMatS/dtool-lookup-gui/pull/135
